/**
 * Investment-project capital-adequacy + tax engine.
 *
 * The user lists assets they'd be willing to use as funding (in priority
 * order). The engine walks the list, working out the smallest amount of
 * each asset needed to cover the project's net-of-tax cost. If the list
 * is exhausted with cost remaining, that's the shortfall.
 */

import { convert } from "./fx";
import {
  parseISO,
  vestedSharesAt,
  type InvestmentProject,
  type Property,
  type Scenario,
  type Settings,
  type StockHolding,
} from "./models";
import { projectPropertyValueAt, projectStockValueAt, resolveReleasePool, resolveScenarioSales } from "./projections";
import { propertySaleTax, stockSaleTax, yearsBetween } from "./tax";

export type FundingLineResult = {
  kind: "stock" | "property" | "cash";
  asset_label: string;
  gross_proceeds: number;
  tax: number;
  net_proceeds: number;
  detail: Record<string, unknown>;
};

export type ProjectEvaluation = {
  project_id: string;
  project_name: string;
  scenario_id: string;
  scenario_name: string;
  target_date: string | null | undefined;
  primary_currency: string;
  total_cost: number;
  funding_lines: FundingLineResult[];
  total_gross: number;
  total_tax: number;
  /** Net proceeds actually drawn down to cover the project (≈ total_cost when funded). */
  total_net_funding: number;
  /** Full post-tax capacity of every listed source whether drawn or not. */
  total_available_net: number;
  /** total_available_net − total_cost. Positive = surplus capacity left over after the project. */
  surplus_or_shortfall: number;
  is_funded: boolean;
};

function resolveTargetDate(p: InvestmentProject): Date {
  if (p.target_date) {
    const d = parseISO(p.target_date);
    if (d) return d;
  }
  return new Date();
}

const fmt0 = new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 });
const fmt2 = new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function evaluateProject(args: {
  project: InvestmentProject;
  scenario: Scenario;
  holdings: StockHolding[];
  properties: Property[];
  settings: Settings;
}): ProjectEvaluation {
  const { project, scenario, holdings, properties, settings } = args;
  const target = resolveTargetDate(project);
  const primary = settings.primary_currency;

  // Total cost in primary currency
  let totalCost = 0;
  for (const item of project.items) {
    totalCost += convert(item.cost, item.currency, primary, settings);
  }

  const holdingsById = new Map(holdings.map((h) => [h.id, h]));
  const propsById = new Map(properties.map((p) => [p.id, p]));

  // Scenario events already earmark shares + cash before the target
  // date. If we don't subtract them, the engine treats shares that the
  // scenario has already sold (or scenario release withholding has
  // taken) as available to fund the project — double-counting.
  const resolvedSales = resolveScenarioSales(scenario, holdings, settings);
  const scenarioSoldByStock = new Map<string, number>();
  const scenarioCashByStock = new Map<string, number>();
  for (const sale of resolvedSales) {
    if (sale.sellDate > target) continue;
    scenarioSoldByStock.set(
      sale.stockId,
      (scenarioSoldByStock.get(sale.stockId) ?? 0) + sale.shares,
    );
    // sale.netPrimary is in settings.primary_currency already.
    scenarioCashByStock.set(
      sale.stockId,
      (scenarioCashByStock.get(sale.stockId) ?? 0) + sale.netPrimary,
    );
  }
  const releasePool = resolveReleasePool(scenario, holdings, settings);
  const scenarioWithheldByStock = new Map<string, number>();
  for (const sr of scenario.releases ?? []) {
    const d = parseISO(sr.release_date);
    if (!d || d > target) continue;
    const resolved = releasePool.get(sr.id);
    if (!resolved) continue;
    const withheld = Math.max(0, resolved.grossShares - resolved.keptShares);
    if (withheld > 0) {
      scenarioWithheldByStock.set(
        sr.stock_id,
        (scenarioWithheldByStock.get(sr.stock_id) ?? 0) + withheld,
      );
    }
  }

  const lines: FundingLineResult[] = [];
  // How much net-of-tax funding we still need. Counts down as each source
  // contributes; once it hits 0, later sources emit zero-use lines.
  let remaining = totalCost;
  // Sum of every listed source's full post-tax capacity, whether drawn or
  // not — drives the headline surplus figure.
  let totalAvailableNet = 0;

  // Implicit funding source: cash the scenario has already generated by
  // target date from planned sales. Tax was already applied at the
  // scenario sale rate — no further tax here. Drawn first so we don't
  // sell more shares before spending money we already have.
  const scenarioCashTotal = Array.from(scenarioCashByStock.values()).reduce(
    (a, b) => a + b,
    0,
  );
  if (scenarioCashTotal > 0.01) {
    const use = remaining > 0 ? Math.min(remaining, scenarioCashTotal) : 0;
    totalAvailableNet += scenarioCashTotal;
    const byStock: Record<string, number> = {};
    for (const [id, amount] of scenarioCashByStock) {
      const h = holdingsById.get(id);
      byStock[h?.ticker || h?.company_name || id] = amount;
    }
    lines.push({
      kind: "cash",
      asset_label: `Scenario cash · ${fmt0.format(scenarioCashTotal)} ${primary} from planned sales by ${target.toISOString().slice(0, 10)}`,
      gross_proceeds: use,
      tax: 0,
      net_proceeds: use,
      detail: {
        cash_available: scenarioCashTotal,
        cash_used: use,
        cash_remaining: scenarioCashTotal - use,
        fully_used: use >= scenarioCashTotal - 0.01,
        by_stock: byStock,
        usage_note: "Implicit — tax already paid at the scenario sale rate.",
        note: use === 0 && remaining <= 0 ? "Not needed — project already funded." : undefined,
      },
    });
    remaining -= use;
  }

  for (const fs of project.funding) {
    if (fs.kind === "cash") {
      // Cash is the only kind where the user must say *how much* they
      // have — it's not derivable from any tracked asset. If the
      // amount is 0/blank we interpret that as "solve for it" — the
      // line reports the exact cash required to close the funding gap,
      // and treats itself as the closing source. Users who genuinely
      // want $0 cash can just remove the funding line instead.
      const cashAvail = Math.max(0, fs.amount_or_shares);
      const isPlaceholder = fs.amount_or_shares === 0 && remaining > 0;
      const use = isPlaceholder
        ? remaining
        : (remaining > 0 ? Math.min(remaining, cashAvail) : 0);
      const effectiveAvail = isPlaceholder ? use : cashAvail;
      totalAvailableNet += effectiveAvail;
      lines.push({
        kind: "cash",
        asset_label: isPlaceholder
          ? `Cash required · ${fmt0.format(use)} ${primary} to close funding gap`
          : `Cash · ${fmt0.format(cashAvail)} ${primary} available`,
        gross_proceeds: use,
        tax: 0,
        net_proceeds: use,
        detail: {
          cash_available: effectiveAvail,
          cash_used: use,
          cash_remaining: effectiveAvail - use,
          fully_used: effectiveAvail > 0 && use >= effectiveAvail,
          is_placeholder: isPlaceholder || undefined,
          usage_note: isPlaceholder
            ? "Blank amount — engine solved for the cash needed to close the gap."
            : undefined,
          note: !isPlaceholder && use === 0 && remaining <= 0
            ? "Not needed — project already funded."
            : undefined,
        },
      });
      remaining -= use;
      continue;
    }

    if (fs.kind === "stock") {
      const h = holdingsById.get(fs.asset_id || "");
      if (!h) {
        lines.push({
          kind: "stock",
          asset_label: "(missing)",
          gross_proceeds: 0,
          tax: 0,
          net_proceeds: 0,
          detail: { error: `Holding ${fs.asset_id} not found` },
        });
        continue;
      }

      const v = projectStockValueAt(h, scenario, target, primary, settings);
      const projectedNative = v.projected_price;
      const rawVested = vestedSharesAt(h, target);
      const scenarioSold = scenarioSoldByStock.get(h.id) ?? 0;
      const scenarioWithheld = scenarioWithheldByStock.get(h.id) ?? 0;
      const scenarioCashFromStock = scenarioCashByStock.get(h.id) ?? 0;
      // Effective liquid pool = vested at target minus what the scenario
      // has already earmarked (withheld at scenario release + sold at
      // scenario sell) by target date.
      const liquidAvail = Math.max(0, rawVested - scenarioSold - scenarioWithheld);
      const costBasis = h.cost_basis_per_share > 0 ? h.cost_basis_per_share : h.current_share_price;
      const holdingPeriod = Math.max(
        0,
        (target.getTime() - Date.now()) / (1000 * 60 * 60 * 24 * 365.25),
      );

      if (liquidAvail <= 0 || projectedNative <= 0) {
        const drained = liquidAvail <= 0 && (scenarioSold > 0 || scenarioWithheld > 0);
        lines.push({
          kind: "stock",
          asset_label: `${h.ticker || h.company_name}`,
          gross_proceeds: 0,
          tax: 0,
          net_proceeds: 0,
          detail: {
            note: drained
              ? `Scenario has already earmarked all shares (${fmt0.format(scenarioSold)} sold, ${fmt0.format(scenarioWithheld)} withheld). Add a cash funding line to route the scenario proceeds.`
              : liquidAvail <= 0
                ? "No liquid shares at target date."
                : "Projected price ≤ 0.",
            shares_available: liquidAvail,
            raw_vested_shares: rawVested,
            scenario_sold_shares: scenarioSold,
            scenario_withheld_shares: scenarioWithheld,
            scenario_cash_from_stock: scenarioCashFromStock,
            projected_price_native: projectedNative,
          },
        });
        continue;
      }

      // For RSUs, apply the scenario's RSU income-tax dropdown as the all-in
      // haircut (matches the projections chart's net-of-tax line). Non-RSU
      // equity goes through the full CGT engine.
      const isRsu = h.equity_type === "RSU";
      const rsuRate = Math.max(0, Math.min(100, scenario.rsu_tax_rate_pct ?? 0)) / 100;

      // Run the tax calc once for the full liquid pool — proceeds and tax
      // are both linear in shares, so net-per-share derived from the full
      // pool is exact for any sub-quantity.
      let txFull = stockSaleTax({
        jurisdiction: project.jurisdiction,
        sale_price_per_share: projectedNative,
        cost_basis_per_share: costBasis,
        shares: liquidAvail,
        holding_period_years: holdingPeriod,
        settings,
      });
      if (isRsu) {
        const grossFull = projectedNative * liquidAvail;
        const taxFull = grossFull * rsuRate;
        txFull = { ...txFull, gross_proceeds: grossFull, tax: taxFull, net_proceeds: grossFull - taxFull };
      }
      const netFullPrimary = convert(txFull.net_proceeds, h.currency, primary, settings);
      totalAvailableNet += netFullPrimary;
      const netPerShare = netFullPrimary / liquidAvail;

      let sharesNeeded = 0;
      if (remaining > 0 && netPerShare > 0) {
        sharesNeeded = Math.min(liquidAvail, Math.ceil(remaining / netPerShare));
      }

      let tx = stockSaleTax({
        jurisdiction: project.jurisdiction,
        sale_price_per_share: projectedNative,
        cost_basis_per_share: costBasis,
        shares: sharesNeeded,
        holding_period_years: holdingPeriod,
        settings,
      });
      if (isRsu) {
        const grossN = projectedNative * sharesNeeded;
        const taxN = grossN * rsuRate;
        tx = { ...tx, gross_proceeds: grossN, tax: taxN, net_proceeds: grossN - taxN };
      }

      const gross_p = convert(tx.gross_proceeds, h.currency, primary, settings);
      const tax_p = convert(tx.tax, h.currency, primary, settings);
      const net_p = convert(tx.net_proceeds, h.currency, primary, settings);

      const label = sharesNeeded > 0
        ? `${h.ticker || h.company_name} — ${fmt0.format(sharesNeeded)} sh @ ~${fmt2.format(projectedNative)} ${h.currency}`
        : `${h.ticker || h.company_name} — not needed`;

      const detail: Record<string, unknown> = { ...tx };
      detail.projected_price_native = projectedNative;
      detail.shares_available = liquidAvail;
      detail.shares_used = sharesNeeded;
      detail.shares_remaining = liquidAvail - sharesNeeded;
      detail.fully_used = sharesNeeded >= liquidAvail;
      const sharePctUsed = liquidAvail > 0 ? (sharesNeeded / liquidAvail) * 100 : 0;
      detail.share_usage_pct = sharePctUsed;
      if (sharesNeeded > 0) {
        detail.usage_note = `${sharePctUsed.toFixed(1)}% of ${fmt0.format(liquidAvail)} available shares used`;
      }
      // Break down where the reductions came from so the user can
      // reconcile against the Sale-math card.
      detail.raw_vested_shares = rawVested;
      if (scenarioSold > 0) detail.scenario_sold_shares = scenarioSold;
      if (scenarioWithheld > 0) detail.scenario_withheld_shares = scenarioWithheld;
      if (scenarioCashFromStock > 0) {
        detail.scenario_cash_from_stock = scenarioCashFromStock;
        detail.scenario_cash_note = `Scenario has already generated ~${fmt0.format(scenarioCashFromStock)} ${primary} of cash from this stock by target — add a cash funding line to route it into the project.`;
      }
      if (isRsu) {
        detail.tax_model = `RSU income tax @ ${(rsuRate * 100).toFixed(0)}% (scenario)`;
      }
      if (remaining > 0 && netPerShare > 0 && sharesNeeded === liquidAvail) {
        detail.warning = `Required all ${fmt0.format(liquidAvail)} liquid shares — still need more funding.`;
      }
      if (remaining <= 0) detail.note = "Not needed — project already funded.";

      lines.push({
        kind: "stock",
        asset_label: label,
        gross_proceeds: gross_p,
        tax: tax_p,
        net_proceeds: net_p,
        detail,
      });
      remaining -= net_p;
      continue;
    }

    if (fs.kind === "property") {
      const p = propsById.get(fs.asset_id || "");
      if (!p) {
        lines.push({
          kind: "property",
          asset_label: "(missing)",
          gross_proceeds: 0,
          tax: 0,
          net_proceeds: 0,
          detail: { error: `Property ${fs.asset_id} not found` },
        });
        continue;
      }

      const vNative = projectPropertyValueAt(p, scenario, target, p.currency, settings);
      const holdingPeriod = yearsBetween(p.purchase_date, target);

      // Net-to-owner scales linearly with fraction sold (sale price, cost
      // basis, and mortgage payoff all scale; the rate is flat). Compute
      // for fully-sold then derive fraction needed.
      const txFull = propertySaleTax({
        jurisdiction: project.jurisdiction,
        sale_price: vNative.gross,
        cost_basis: p.purchase_price,
        holding_period_years: holdingPeriod,
        mortgage_balance: p.mortgage_balance,
        is_primary_residence: false,
        settings,
      });
      const netFullPrimary = convert(txFull.net_to_owner, p.currency, primary, settings);
      totalAvailableNet += Math.max(0, netFullPrimary);

      if (netFullPrimary <= 0) {
        lines.push({
          kind: "property",
          asset_label: `${p.name}`,
          gross_proceeds: 0,
          tax: 0,
          net_proceeds: 0,
          detail: {
            note: "No equity at target date (mortgage ≥ projected value, or sale yields nothing after tax).",
            projected_value_native: vNative.gross,
          },
        });
        continue;
      }

      let fraction = 0;
      if (remaining > 0) {
        fraction = Math.min(1, remaining / netFullPrimary);
      }

      const salePriceNative = vNative.gross * fraction;
      const costBasisNative = p.purchase_price * fraction;
      const mortgageNative = p.mortgage_balance * fraction;

      const tx = propertySaleTax({
        jurisdiction: project.jurisdiction,
        sale_price: salePriceNative,
        cost_basis: costBasisNative,
        holding_period_years: holdingPeriod,
        mortgage_balance: mortgageNative,
        is_primary_residence: false,
        settings,
      });

      const gross_p = convert(tx.sale_price, p.currency, primary, settings);
      const tax_p = convert(tx.tax, p.currency, primary, settings);
      const net_p = convert(tx.net_to_owner, p.currency, primary, settings);

      const pctSold = fraction * 100;
      const label = fraction > 0
        ? `${p.name} — sell ${pctSold.toFixed(1)}% @ ~${fmt0.format(salePriceNative)} ${p.currency}`
        : `${p.name} — not needed`;

      const detail: Record<string, unknown> = {
        ...tx,
        fraction_used: fraction,
        fraction_remaining: 1 - fraction,
        fully_used: fraction >= 1,
        holding_period_years: Number(holdingPeriod.toFixed(2)),
      };
      if (remaining > 0 && fraction === 1) {
        detail.warning = `Fully selling property only yields ${fmt0.format(netFullPrimary)} ${primary} — still need more funding.`;
      }
      if (remaining <= 0) detail.note = "Not needed — project already funded.";

      lines.push({
        kind: "property",
        asset_label: label,
        gross_proceeds: gross_p,
        tax: tax_p,
        net_proceeds: net_p,
        detail,
      });
      remaining -= net_p;
      continue;
    }
  }

  const totalGross = lines.reduce((s, l) => s + l.gross_proceeds, 0);
  const totalTax = lines.reduce((s, l) => s + l.tax, 0);
  const totalNet = lines.reduce((s, l) => s + l.net_proceeds, 0);

  return {
    project_id: project.id,
    project_name: project.name,
    scenario_id: scenario.id,
    scenario_name: scenario.name,
    target_date: project.target_date,
    primary_currency: primary,
    total_cost: totalCost,
    funding_lines: lines,
    total_gross: totalGross,
    total_tax: totalTax,
    total_net_funding: totalNet,
    total_available_net: totalAvailableNet,
    // Surplus reflects the leftover capacity from EVERY listed source
    // (whether drawn down or not), so the user can see how much of their
    // available pool remains after the project.
    surplus_or_shortfall: totalAvailableNet - totalCost,
    // Allow a tiny rounding tolerance — sharesNeeded uses Math.ceil, so
    // we can be a fraction of a share over the cost.
    is_funded: totalAvailableNet >= totalCost - 0.01,
  };
}
